/// Pure Dart constants for app/collection types
/// This file has no Flutter dependencies so it can be used in CLI mode

/// All known app/collection types that can be routed to via URL
/// This is the canonical list used for URL routing and collection management
const List<String> knownAppTypesConst = [
  'www',
  'blog',
  'chat',
  'email',
  'forum',
  'events',
  'alerts',
  'places',
  'files',
  'contacts',
  'transfer',
  'groups',
  'news',
  'postcards',
  'market',
  'station',
  'documents',
  'photos',
  'inventory',
  'wallet',
  'log',
  'backup',
  'console',
  'tracker',
  'videos',
  'reader',
  'work',
  'usenet',
  'music',
  'stories',
  'qr',
];

/// App types that can only have a single instance per profile
/// Used by CreateCollectionPage to prevent duplicate creation
/// and by main.dart to show default apps
const Set<String> singleInstanceTypesConst = {
  'forum',
  'chat',
  'blog',
  'email',
  'events',
  'news',
  'www',
  'postcards',
  'places',
  'market',
  'alerts',
  'groups',
  'backup',
  'transfer',
  'inventory',
  'wallet',
  'log',
  'console',
  'tracker',
  'contacts',
  'videos',
  'reader',
  'flasher',
  'work',
  'usenet',
  'music',
  'stories',
  'files',
  'qr',
};

/// Predefined categories for stories
const List<String> storyCategoriesConst = [
  'news',
  'fun',
  'tech',
  'adult',
  'diary',
  'geocache',
  'travel',
  'tutorial',
  'gaming',
  'food',
  'fitness',
  'art',
  'music',
  'nature',
  'history',
  'science',
  'business',
  'family',
  'pets',
  'diy',
  'mystery',
  'romance',
  'horror',
  'fantasy',
];

/// Icon names for story categories (used to look up Icons.* constants)
const Map<String, String> storyCategoryIconNames = {
  'news': 'newspaper',
  'fun': 'celebration',
  'tech': 'computer',
  'adult': 'no_adult_content',
  'diary': 'menu_book',
  'geocache': 'explore',
  'travel': 'flight',
  'tutorial': 'school',
  'gaming': 'sports_esports',
  'food': 'restaurant',
  'fitness': 'fitness_center',
  'art': 'palette',
  'music': 'music_note',
  'nature': 'park',
  'history': 'history_edu',
  'science': 'science',
  'business': 'business',
  'family': 'family_restroom',
  'pets': 'pets',
  'diy': 'build',
  'mystery': 'quiz',
  'romance': 'favorite',
  'horror': 'mood_bad',
  'fantasy': 'auto_fix_high',
};
